ABOnline/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.views.static import serve
import xadmin
from django.views.generic import TemplateView
from users.views import LoginView, RegisterView, refresh_captcha, ActiveUserView, ForgetPwdView, ResetView, ModifyPwdView
from organization.views import OrganizationInView, OrgBaseView
from ABOnline.settings import MEDIA_ROOT


urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    # url(r'^login/$', TemplateView.as_view(template_name='login.html'), name='login'),
    # url(r'^login/$', user_login, name='login'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^refresh_captcha/', refresh_captcha, name='refresh_captcha'),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='user_active'),
    url(r'^forget/$', ForgetPwdView.as_view(), name='forget_pwd'),
    url(r'^reset/(?P<active_code>.*)/$', ResetView.as_view(), name='reset_pwd'),
    url(r'^modify/$', ModifyPwdView.as_view(), name='modify_pwd'),
    # 个人中心
    url(r'^user/', include('users.urls', namespace='users')),
    # 课程机构url配置
    url(r'^org/', include('organization.urls', namespace='org')),
    # 课程url配置
    url(r'^course/', include('courses.urls', namespace='course')),
    # 配置上传文件的访问处理函数
    url(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),

    # url(r'^org_base/$', OrgBaseView.as_view(), name='org_base')
]

apps/courses/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'wowoqu'
__date__ = '2018/6/18 23:13'

from django.conf.urls import url, include
from .views import CourseListView, CourseDetailView, CourseVedioView, AddComment, VideoPlayView, TeacherListView, \
    TeacherDetailView


app_name = 'courses'
urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name='course_list'),
    # 课程详情页
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name='course_detail'),
    url(r'^vedio/(?P<course_id>\d+)/$', CourseVedioView.as_view(), name='course_vedio'),
    url(r'^add_comments/$', AddComment.as_view(), name='add_comments'),
    url(r'^video/(?P<video_id>\d+)/$', VideoPlayView.as_view(), name='video_play'),
    url(r'^teacher/$', TeacherListView.as_view(), name='teacher_list'),
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/organization/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'wowoqu'
__date__ = '2018/6/16 13:05'
from django.conf.urls import url, include

from .views import OrganizationInView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView, AddFavView

app_name = 'organization'
urlpatterns = [
    url(r'^list/$', OrganizationInView.as_view(), name='org_list'),
    url(r'^add_ask/$', AddUserAskView.as_view(), name='add_ask'),
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name='org_home'),
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name='org_course'),
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name='org_desc'),
    url(r'^teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name='org_teacher'),

    # 机构收藏
    url(r'^add_fav/$', AddFavView.as_view(), name='add_fav'),
]

apps/users/urls.py
# _*_ coding: utf-8 _*_
__author__ = 'wowoqu'
__date__ = '2018/6/28 15:56'

from django.conf.urls import url, include
from .views import UserHomeView, UploadImageView, UpdatePwdView, SendEmailCodeView, UpdateEmailView, MyCourseView, \
    MyFavOrgView

app_name = 'users'
urlpatterns = [
    url(r'^home/$', UserHomeView.as_view(), name='user_home'),
    url(r'^image/upload/$', UploadImageView.as_view(), name='image_upload'),
    # 用户个人中心修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name='update_pwd'),
    url(r'sendemail_code/$', SendEmailCodeView.as_view(), name='sendemail_code'),
    url(r'update_email/$', UpdateEmailView.as_view(), name='update_email'),
    # 我的课程
    url(r'mycourse/$', MyCourseView.as_view(), name='my_course'),
    # 我的课程收藏
    url(r'myfavorg/$', MyFavOrgView.as_view(), name='my_favorg'),
]

apps/courses/models.py
from django.db import models
from datetime import datetime
from organization.models import CourseOrg, Teacher


# Create your models here.


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name='课程机构', null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, verbose_name='课程名')
    desc = models.CharField(max_length=300, verbose_name='课程描述')
    detail = models.TextField(verbose_name='课程详情')
    teacher = models.ForeignKey(Teacher, verbose_name='讲师', null=True, blank=True, on_delete=models.CASCADE)
    degree = models.CharField(choices=(('cj', '初级'), ('zj', '中级'), ('gj', '高级')), max_length=2)
    learn_times = models.IntegerField(default=0, verbose_name='学习时长(分钟数)')
    students = models.IntegerField(default=0, verbose_name='学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏人数')
    image = models.ImageField(upload_to='courses/%Y/%m', verbose_name='封面图', max_length=100)
    click_num = models.IntegerField(default=0, verbose_name='点击数')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    category = models.CharField(max_length=20, verbose_name='课程类别', default='后台开发')
    tag = models.CharField(default='', verbose_name='课程标签', max_length=10)
    youneed_know = models.CharField(default='', max_length=300, verbose_name='课程须知')
    teacher_tell = models.CharField(default='', max_length=300, verbose_name='老师告诉你')

    class Meta:
        verbose_name = '课程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name
    # 章节数

    def get_zj_nums(self):
        return self.lesson_set.all().count()

    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        # 获取课程所有章节
        return self.lesson_set.all()

    def get_course_resource(self):
        return self.courseresource_set.all()


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='课程')
    name = models.CharField(max_length=100, verbose_name='章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_vedio(self):
        return self.video_set.all()


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, verbose_name='章节名')
    name = models.CharField(max_length=100, verbose_name='视频名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    url = models.CharField(max_length=200, verbose_name='访问地址', default='')
    learn_times = models.IntegerField(default=0, verbose_name='学习时长(分钟数)')

    class Meta:
        verbose_name = '视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='课程')
    name = models.CharField(max_length=100, verbose_name='名称')
    download = models.FileField(upload_to='course/resource/%Y/%m', verbose_name='资源文件', max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta:
        verbose_name = '课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/course-vedio.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block title %}
    公开课视频信息
{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/course-vedio.css' %}">
{% endblock %}
{% block content %}
    <section class="container org-list" style="position: relative">
        {% block video_play %}
            <div class="org-head">
                <p class="bred"><a href="{% url 'index' %}">首页></a><a href="{% url 'course:course_list' %}">公开课程></a><a
                        href="{% url 'course:course_list' %}">课程详情></a><i>章节信息</i></p>
            </div>
            <div class="total">
                <h1>{{ course.name }}</h1>
                <ul>
                    <li><h2>{{ course.get_degree_display }}</h2>
                        <p>难度</p></li>
                    {#                <li><h2>7<span>小时</span>0<span>分</span></h2><p>时长</p></li>#}
                    <li><h2>{{ course.learn_times }}分钟</h2>
                        <p>时长</p></li>
                    <li><h2>{{ course.students }}</h2>
                        <p>学习人数</p></li>
                </ul>
            </div>
        {% endblock %}
        <div class="mid-cont">
            <div class="lesson-left">
                <ul>
                    <li class="active" id="comment">评论</li>
                    <li id="lesson">章节</li>
                </ul>
                <div class="lesson-cont" style="display: none">
                    <p><span>课程公告：</span>Spring的文档以及相关的jar文件已上传</p>
                    <dl>
                        {% for lesson in course.get_course_lesson %}
                            <dt>{{ lesson.name }}</dt>
                            {% for vedio in lesson.get_vedio %}
                                <dd><a href="{% url 'course:video_play' vedio.id %}">{{ vedio.name }}({{ vedio.learn_times }})</a></dd>
                            {% endfor %}
                        {% endfor %}
                    </dl>
                </div>
                <div class="comment-conf">
                    <textarea name="" id="js-comment" cols="30" rows="10"
                              placeholder="扯淡、吐槽、表扬、鼓励......想说啥就说啥！"></textarea>
                    <button id="comm-submit">发表评论</button>
                    {% for comment in all_comments.object_list %}
                        <div class="user-comm">
                            <img src="/media/{{ comment.user.image }}" alt="">
                            <div class="comm-right">
                                <h1>{{ comment.user.username }}</h1>
                                <p>{{ comment.comments }}</p>
                                <span style="display:block;margin-bottom: 10px">时间：{{ comment.add_time }}</span>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="comment-list">
                        <ul>
                            {% if all_comments.has_previous %}
                                <li class="spec"><a href="?{{ all_comments.previous_page_number.querystring }}"
                                >上一页</a></li>
                            {% endif %}
                            {% for page in all_comments.pages %}
                                {% if page %}
                                    {% ifequal page all_comments.number %}
                                        <li class="active"><a href="">{{ page }}</a></li>
                                    {% else %}
                                        <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                    {% endifequal %}
                                {% else %}
                                    <li><a href="">...</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if all_comments.has_next %}
                                <li class="spec"><a href="?{{ all_comments.next_page_number.querystring }}">下一页</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="down-right">
                <h1>资料下载</h1>
                {% for resource in course.get_course_resource %}
                    <div class="le-re">
                        <p>{{ resource.name }}</p>
                        <div><a href="/media/{{ resource.download }}">下载</a></div>
                    </div>
                {% endfor %}
                <h1>讲师提示</h1>
                <div class="teacher">
                    <a href=""><img src="/media/{{ course.teacher.image }}" alt=""></a>
                    <h3>{{ course.teacher.name }}</h3>
                    <p>{{ course.teacher.work_position }}</p>
                </div>
                <div class="you_know">
                    <dl>
                        <dt>课程须知</dt>
                        <dd>{{ course.youneed_know }}</dd>
                        <dt>老师告诉你能学到什么？</dt>
                        <dd>{{ course.teacher_tell }}</dd>
                    </dl>
                </div>
                {% for relate_course in relate_courses %}
                    <h1>该课程的同学还学过</h1>
                    <a style="display: block;width: 100%;height: 120px;margin: 10px 0;" href=""><img
                            style="width: 100%;height: 100%;" src="/media/{{ relate_course.image }}" alt=""></a>
                    <p>{{ relate_course.name }}</p>
                {% endfor %}
            </div>
        </div>
        <div style="height: 20px;"></div>
    </section>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript">
        $(function () {
            $('#lesson').bind('click', function () {
                $('.comment-conf').css('display', 'none');
                $('.lesson-cont').css('display', 'block');
                $(this).addClass('active').siblings().removeClass('active');
                {#console.log(1)#}
            });
            $('#comment').bind('click', function () {
                $('.comment-conf').css('display', 'block');
                $('.lesson-cont').css('display', 'none');
                $(this).addClass('active').siblings().removeClass('active');
                {#console.log(2)#}
            });
            $('#comm-submit').on('click', function () {
                var comments = $('#js-comment').val();
                if (comments == '') {
                    alert('评论不能为空');
                    return
                }
                $.ajax({
                    cache: false,
                    type: 'POST',
                    url: "{% url "course:add_comments" %}",
                    data: {'course_id': {{ course.id }}, 'comments': comments},
                    async: true,
                    beforeSend: function (xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}")
                    },
                    success: function (data) {
                        console.log(data.msg);
                        console.log(data.status);
                        if (data.status == 'fail') {
                            if (data.msg == '用户未登陆') {
                                window.location.href = '/login/';
                            } else {
                                alert(data.msg)
                            }
                        } else if (data.status == 'success') {
                            alert('成功');
                            $('#js-comment').val("");
                            window.location.reload();
                            $('#comment').addClass('active').siblings().removeClass('active');
                        }
                    }
                });
            });
        })
    </script>
{% endblock %}

templates/org_desc.html
{% extends 'index_base.html' %}
{% block title %}
    机构介绍
{% endblock %}
{% block page_path %}
    机构介绍
{% endblock %}
{% block right_content %}
    <div class="bs-div" style="overflow: hidden">
        <h1>机构介绍</h1>
        <div class="bs-content">
            {{ course_org.desc }}
        </div>
    </div>
{% endblock %}

templates/user-course.html
{% extends 'org_course.html' %}
{% load staticfiles %}
{% block title %}
    我的课程
{% endblock %}
{% block logo %}
    <div class="container logo-search">
        <img class="logo" src="{% static 'images/logo.png' %}" alt="">
        <h1 style="margin-right: 20px">个人首页</h1>
    </div>
{% endblock %}
{% block coustom_bread %}
    <section class="container org-list" style="position: relative">
        <div class="org-head">
            <p class="bred"><a href="{% url 'index' %}">首页></a><i><a href="{% url 'users:user_home' %}">个人中心></a></i><i>{% block page_path %}我的课程{% endblock %}</i></p>
        </div>
    </section>
{% endblock %}
{% block left_content %}
    <ul>
        <li class="{% ifequal current_page 'home' %}active{% endifequal %}"><a
                href="{% url 'users:user_home' %}">个人资料</a></li>
        <li class="{% ifequal current_page 'course' %}active{% endifequal %}"><a
                 href="{% url 'users:my_course' %}">我的课程</a></li>
        <li class="{% ifequal current_page 'favorg' %}active{% endifequal %}"><a
                 href="{% url 'users:my_favorg' %}">我的收藏</a></li>
        <li class="{% ifequal current_page 'teacher' %}active{% endifequal %}"><a
                 href="">我的消息</a></li>
    </ul>
{% endblock %}
{% block right_content %}
    <div class="bs-div">
        <h1>全部课程</h1>
        <div class="bs-content">
            {% for usercourse in user_courses.object_list %}
                <div class="content-div">
                    <a href="{% url 'course:course_detail' usercourse.course_id %}"><img src="/media/{{ usercourse.course.image }}" alt=""></a>
                    <h1>{{ usercourse.course.name }}</h1>
                    <div style="overflow: hidden">
                        <span style="float: left;margin-bottom: 20px">价格：<i>免费</i></span>
                        <span style="float: right;margin-bottom: 20px">学习人数：<i>{{ usercourse.course.students }}</i></span>
                    </div>
                    <p style="float:left;">{{ usercourse.course.course_org.name }}</p>
                    <p style="float:right;">{{ usercourse.course.fav_nums }}</p>
                </div>
            {% endfor %}
            <div class="paging-list">
            <ul>
                {% if user_courses.has_previous %}
                    <li class="spec"><a href="?{{ user_courses.previous_page_number.querystring }}"
                    >上一页</a></li>
                {% endif %}
                {% for page in user_courses.pages %}
                    {% if page %}
                        {% ifequal page user_courses.number %}
                            <li class="active"><a href="">{{ page }}</a></li>
                        {% else %}
                            <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                        {% endifequal %}
                    {% else %}
                        <li><a href="">...</a></li>
                    {% endif %}
                {% endfor %}
                {% if user_courses.has_next %}
                    <li class="spec"><a href="?{{ user_courses.next_page_number.querystring }}">下一页</a></li>
                {% endif %}
            </ul>
        </div>
        </div>
    </div>
{% endblock %}

templates/user_home.html
{% extends 'index_base.html' %}
{% load staticfiles %}
{% load staticfiles %}
{% block title %}
    个人中心
{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/org_base.css' %}">
    <link rel="stylesheet" href="{% static 'css/user_home.css' %}">
    <script src="http://lib.sinaapp.com/js/jquery/2.0.2/jquery-2.0.2.min.js"></script>
{% endblock %}
{% block logo %}
        <div class="container logo-search">
            <img class="logo" src="{% static 'images/logo.png' %}" alt="">
            <h1 style="margin-right: 20px">个人首页</h1>
        </div>
{% endblock %}
{% block coustom_bread %}
    <section class="container org-list" style="position: relative">
        <div class="org-head">
            <p class="bred"><a href="{% url 'index' %}">首页></a><i><a href="{% url 'users:user_home' %}">个人中心></a></i><i>{% block page_path %}个人信息{% endblock %}</i></p>
        </div>
    </section>
{% endblock %}
{% block left_content %}
    <ul>
        <li class="{% ifequal current_page 'home' %}active{% endifequal %}"><a
                href="{% url 'users:user_home' %}">个人资料</a></li>
        <li class="{% ifequal current_page 'course' %}active{% endifequal %}"><a
                 href="{% url 'users:my_course' %}">我的课程</a></li>
        <li class="{% ifequal current_page 'favorg' %}active{% endifequal %}"><a
                 href="{% url 'users:my_favorg' %}">我的收藏</a></li>
        <li class="{% ifequal current_page 'teacher' %}active{% endifequal %}"><a
                 href="">我的消息</a></li>
    </ul>
{% endblock %}

{% block right_content %}
    <div class="bs-div" style="overflow: hidden;">
        <h1>个人信息</h1>
        <div style="display: flex;">
            <div class="left1">
                <div>
                    <form action="{% url 'users:image_upload' %}" enctype="multipart/form-data" method="post" id="jsChangeForm">
                        <img  id="jsChangeImg" src="/media/{{ user.image }}" alt="">
                        <p style="position: relative;">修改头像<input id="jsChangeFile" name="image" type="file"></p>
                        {% csrf_token %}
                    </form>
                </div>
                <div>
                    <p id="jsDnPass">修改密码</p>
                </div>
            </div>
            <div class="right1">
                <form action="{% url 'users:user_home' %}" method="post" id="jsUserForm">
                    <div>
                        昵&nbsp;&nbsp;&nbsp;&nbsp;称：<input type="text" name="nick_name" value="{{ user.nick_name }}">
                    </div>
                    <div>
                        生&nbsp;&nbsp;&nbsp;&nbsp;日：<input id="jsDate" name="birthday" type="date" value="{{ user.birthday }}">
                    </div>
                    <div>
                        性&nbsp;&nbsp;&nbsp;&nbsp;别：  <input type="radio" name="gender" value="male" {% if user.gender == 'male' %}
                            checked="checked
                        {% endif %}"> 男
                                  <input type="radio" name="gender" value="female" {% if user.gender == 'female' %}
                            checked="checked
                        {% endif %}"> 女<br>
                    </div>
                    <div>
                        地&nbsp;&nbsp;&nbsp;&nbsp;址：<input type="text" name="address" value="{{ user.address }}">
                    </div>
                    <div>
                        手&nbsp;&nbsp;&nbsp;&nbsp;机：<input type="text" name="mobile" value="{{ user.mobile|default_if_none:'' }}">
                    </div>
                    <div>
                        邮&nbsp;&nbsp;&nbsp;&nbsp;箱：<input type="email" value="{{ user.email }}">&nbsp;&nbsp;<span id="jsChangeEmail" style="display: inline-block;cursor: pointer">[修改]</span>
                    </div>
                    <p class="bc-user">保存</p>
                {% csrf_token %}
                </form>
            </div>
        </div>
        <div class="reset-pass" id="jsResetPass">
            <div class="re-head">
                <h1>修改密码</h1>
                <div id="close">x</div>
            </div>
            <form action="{% url 'users:update_pwd' %}" method="post" id="jsPassForm">
                <input type="password" placeholder="请输入密码" name="password" id="jsPass1"><br>
                <input type="password" placeholder="请重新输入密码" name="re_password" id="jsPass2">
                <p id="jsPassSub">提交</p>
                {% csrf_token %}
            </form>
        </div>
        <div id="jsCgEmail" class="reset-pass">
            <div class="re-head">
                <h1>修改邮箱</h1>
                <div id="jsEmailClose">x</div>
            </div>
            <form id="jsEmailForm">
                <input type="email" placeholder="请输入邮箱" name="email"><br>
                <span style="position: relative;">
                    <input type="text" placeholder="" name="code" style="margin-top: 0px">
                    <div id="jsGetCode" style="position: absolute;top: -7px;cursor: pointer;color:#fcfcfc;right:0px;padding: 6px 16px;background: orange;">获取验证码</div>
                </span>
                <p id="jsEmailPass">提交</p>
                {% csrf_token %}
            </form>
        </div>
    </div>
    <div style="position: fixed">
        <h1 id="ss">修改密码</h1>
    </div>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/jquery.form.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#jsChangeFile').change(function () {
                var filePath = $(this).val();//读取图片路径
                console.log(filePath)
                var fr = new FileReader();//创建new FileReader()对象
                console.log(fr)
                var imgObj = this.files[0];//获取图片
                console.log(imgObj)
                fr.readAsDataURL(imgObj);//将图片读取为DataURL
                var obj = $('#jsChangeImg')[0];//

                if(filePath.indexOf("jpg") != -1 || filePath.indexOf("JPG") != -1 || filePath.indexOf("PNG") != -1 || filePath.indexOf("png") != -1  || filePath.indexOf("jpeg") != -1) {
                    var arr = filePath.split('\\');
                    var fileName = arr[arr.length - 1];

                    {#$(this).parent().next().show();#}
                    fr.onload = function() {
                        obj.src = this.result;
                    };
                } else {
                    console.log('error');
                    //$(this).parent().next().show();
                    //$(this).parent().next().children("i").html("您未上传文件，或者您上传文件类型有误！").css("color", "red");
                    //$(this).parent().next().html("您未上传文件，或者您上传文件类型有误！").css("color","red");
                    return false
                }
                var options = {
                    url: "{% url 'users:image_upload' %}",  //提交地址：默认是form的action,如果申明,则会覆盖
                    type: "post",   //默认是form的method（get or post），如果申明，则会覆盖
                    success: function (data) {
                        if(data.status == 'success'){
                            console.log('提交成功');
                        }else if(data.status == 'fail'){
                            console.log('提交失败');
                        }
                    },  //提交成功后的回调函数
                    dataType: "json", //html(默认), xml, script, json...接受服务端返回的类型
                    clearForm: true,  //成功提交后，是否清除所有表单元素的值
                    resetForm: true,  //成功提交后，是否重置所有表单元素的值
                    timeout: 3000     //限制请求的时间，当请求大于3秒后，跳出请求
                };
                $('#jsChangeForm').ajaxSubmit(options);
            });
            $('#jsDnPass').bind('click', function () {
                $('#jsResetPass').css('display', 'block');
            });
            $('#close').bind('click', function () {
                $('#jsResetPass').css('display', 'none');
            });
            $('#jsPassSub').on('click',function () {
                $('#jsPassForm').ajaxSubmit(function (data) {
                    if(data.status == 'success'){
                        console.log('提交成功');
                        $('#jsResetPass').css('display', 'none');
                    } else if(data.status == 'fail'){
                        console.log(data.msg);
                    } else if(data.password){
                        console.log(data);
                    }
                });
            });
            $('#jsChangeEmail').bind('click', function () {
                $('#jsCgEmail').show()
            });
            $('#jsEmailClose').bind('click', function () {
                $('#jsCgEmail').hide()
            });
            //格式化日，如果小于9，前面补0
            var day = ("0" + {{ user.birthday.day }}).slice(-2);
            //格式化月，如果小于9，前面补0
            var month = ("0" + {{ user.birthday.month }}).slice(-2);
            //拼装完整日期格式
            var today = {{ user.birthday.year }}+"-"+(month)+"-"+(day) ;
            //完成赋值
            $('#jsDate').val(today);
            $('#jsGetCode').bind('click', function () {
                console.log('click');
                $.ajax({
                    type: 'get',
                    url: "{% url "users:sendemail_code" %}",
                    data: {"email":$('#jsEmailForm input[type="email"]').val()},
                    async: true,
                    success: function (data) {
                        console.log(data);
                        if(data.status == 'success'){
                            {#$('#jsEmailForm')[0].reset();#}
                            console.log('提交成功');
                        }else if(data.status == 'fail'){
                            {#console.log(data.email);#}
                            console.log('提交失败');
                        }
                    }
                })
            });
            $('#jsEmailPass').bind('click', function () {
                console.log('tijiao')
                var options = {
                    url: "{% url 'users:update_email' %}",  //提交地址：默认是form的action,如果申明,则会覆盖
                    type: "post",   //默认是form的method（get or post），如果申明，则会覆盖
                    success: function (data) {
                        console.log(data.email);
                    },  //提交成功后的回调函数
                    dataType: "json", //html(默认), xml, script, json...接受服务端返回的类型
                    clearForm: true,  //成功提交后，是否清除所有表单元素的值
                    resetForm: true,  //成功提交后，是否重置所有表单元素的值
                    timeout: 3000     //限制请求的时间，当请求大于3秒后，跳出请求
                };
                $('#jsEmailForm').ajaxSubmit(options);
            });
            $('.bc-user').bind('click',function () {
                $('#jsUserForm').ajaxSubmit(function (data) {
                    console.log(data.msg + '110');
                    alert('个人信息修改成功');
                    return false;
                })
            })
        })
    </script>
{% endblock %}